spring:
  application:
    name: dobraszwalnia-time-service
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:timeService
    username: sa
    password:
    driver:
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto=create: create-drop
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: /roles.sql

server:
  port: 8089
